### ISSUE TITLE
ValueError occured when running server.py

### ISSUE THREAD

**Issue by lnyxzdevk** [iwalton3/mpt-lora-patch#2]
When using webui, copy the files in this repo and also apply the modifications written in the README. But, following error occurs when I running server.py with your command in README.
```
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.
```
Is there any solution?

**Comment by iwalton3** [comment]
I don't think it is caused by this code base, but using --gpu [no of GB VRAM] worked for me

**Comment by lnyxzdevk** [comment]
It works!! Thank you so much :)
